### PR TITLE
Asset fix

### PR DESCRIPTION
**Pull request by noguespi**
Fix AssetsController vulnerability, without removing static files feature.

Now when the controller serves a static files, it always check the files is in the assetBaseDir

### CODE REVIEW

**Comment by liudianpeng** [comment]
what???????????

**Comment by noguespi** [comment]
@liudianpeng related to https://groups.google.com/forum/#!topic/ninja-framework/Go97aKNWoCw

**Comment by liudianpeng** [comment]
@serphacker I would like to consult with the redirectt Ninja

**Comment by liudianpeng** [comment]
I would like to consult with the redirect Ninja

**Pull request closed without merging**
