### PR TITLE
Upgrade to hibernate 5

### PR DESCRIPTION
**Pull request by asolntsev**
based on another PR https://github.com/ninjaframework/ninja/pull/708 (branch `upgrade-dependencies`).

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Just fyi: Mid-Term Hibernate should no longer be part of Ninja, but of Ninja-Db. Ninja-Db living here: https://github.com/ninjaframework/ninja-db . It already got support for jdbi, and you could use that as boilerplate to add Hibernate...

**Comment by asolntsev** [comment]
@raphaelbauer Wow, I didn't know that, thanks. 
But shouldn't we remove Hibernate dependency from https://github.com/ninjaframework/ninja then?

**Comment by raphaelbauer** [comment]
That was roughly the plan for Ninja 7. Making it a lot smaller. We could then also remote Flyway and all db related dependencies from the core...

**Comment by raphaelbauer** [comment]
Let me know if we can help in any way :)

**Pull request closed without merging**
