### PR TITLE
support delimiter config for i18n message file

### PR DESCRIPTION
**Pull request by amsz**
Adresses issue #118

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Hi,

thanks a lot for the pull request!
Would be great if you could add testcases to the code. We just need testcases to make Ninja a stable platform. I think a mocked test is sufficient.

Second, please add some documentation (18n section), a simple explanation to the changelog and yourself to the team.md page...

More about the locations of the documentation files is here: http://www.ninjaframework.org/developer/getting_started.html

In any case a very good remark and pull request :)

Thanks!

Raphael

**Comment by amsz** [comment]
Ok, I will read document of developer and pull a new request.

**Comment by raphaelbauer** [comment]
Cool. Let me know if I can help. You can use the same request. Just push your changes  to this request... no need for a new one :)

**Comment by raphaelbauer** [comment]
Hey @amsz ,

I added your feature to Ninja. Actually I followed your idea and "_" will become the default and only way how to handle properties files. It's just a lot simpler to translate them via Netbeans (in my case).

I added you as contributor and also to the changelog :+1: 

Thanks!

Raphael

**Pull request closed without merging**
