### PR TITLE
added quartz scheduler module

### PR DESCRIPTION
**Pull request by svenkubiak**
I have created a quartz scheduler module (https://github.com/svenkubiak/ninja-quartz) and added it to the modules page.

### CODE REVIEW

**Comment by raphaelbauer** [comment]
nice!

**Comment by danielsawan** [comment]
Do you have abandoned this module ?

**Comment by svenkubiak** [comment]
@danielsawan 
Yes, I have stopped developing on all my ninja modules.

**Comment by danielsawan** [comment]
oh :( damn. I wanted to use your module to solve my issue https://github.com/ninjaframework/ninja/issues/375

 Sorry for asking that but is there a reason to that ? (for leaving i mean).

**Comment by raphaelbauer** [comment]
@svenkubiak  is there a reason why you completely deleted the code? It would be cool if you could leave it online in case someone wants to fork it - or learn from it :) You can still mark it as "abandoned" so that people know...

**Comment by svenkubiak** [comment]
@danielsawan 
The main reason is, that I develop my own full stack java framework, which basically included the scheduler, etc. As I focus on that now I wont have any time to maintain the ninja modules.

@raphaelbauer 
I admit, just deleting the Repos was a bit overhasty, but I wanted a clean GitHub account :-D
Anyway, I still have the code if someone is interested.

**Comment by danielsawan** [comment]
@svenkubiak 
Oh ok i see thanks for your answer. It would be cool if i can fork it. I hope it will not take much from your time. Btw @raphaelbauer it could be interesting to fork interesting community mades modules (i think quartz module is) directly to the ninjaframework repo in order to save the codes. (with the permissions of module's owner for sure)

Many modules are hosted at the user's own repo 
http://www.ninjaframework.org/documentation/modules.html

Thanks for your help sven and good luck with mangooio
I will test this for sure when it get more mature.

**Comment by raphaelbauer** [comment]
mangooio sounds cool! All the best :+1:

**Pull request merged**
