### PR TITLE
Add result support for route

### PR DESCRIPTION
**Pull request by amsz**
simply define a route:

<pre>
router.GET().route("/redirect").with(Results.redirect("/xx"));
</pre>

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Very good work!

**Comment by raphaelbauer** [comment]
@amsz Hey, unfortunately I had to revert the merge. Seems like there are some errors after merging (https://buildhive.cloudbees.com/job/ninjaframework/job/ninja/org.ninjaframework$ninja-servlet-integration-test/132/). Could you have a look? It also happens locally on my machine when running a simple "mvn clean install".

Thanks!

**Comment by raphaelbauer** [comment]
Ah and once that's fixed could you also add your change to changelog.md? Thanks! :+1:

**Comment by amsz** [comment]
Ok, I try run it quickly.

-- 
xiaochen

开启 2014年2月7日 at 21:58:38, Raphael A. Bauer (notifications@github.com) 写:

@amsz Hey, unfortunately I had to revert the merge. Seems like there are some errors after merging. Could you have a look? It also happens locally on my machine when running a simple "mvn clean install".

Thanks!

**Comment by raphaelbauer** [comment]
Perfect! Let me know if I can help :)

**Comment by amsz** [comment]
Please test again, my local tests all pass.

**Comment by raphaelbauer** [comment]
Works now like a charm!
Is merged :)

**Pull request merged**
