### PR TITLE
Feature validation enhancement

### PR DESCRIPTION
**Pull request by jlannoy**
#549
First proposal for a short refactoring of the Validation handler.

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Nice work @jlannoy ! 
I'd like to give it a deep dive - but I am a bit busy with work right now. @jjlauer do you have time to review the code? If not - I'll do my best to review it the coming days...

**Comment by jjlauer** [comment]
@jlannoy @raphaelbauer This PR looks good to me.

**Comment by raphaelbauer** [comment]
Looks also good to me :) Very nice work @jlannoy  Validation was always an area in Ninja that was confusing. Now it looks a lot better thanks to your effort!

**Comment by raphaelbauer** [comment]
👍

**Pull request merged**
