### PR TITLE
Bug #303 - JSON / XML body parser

### PR DESCRIPTION
**Pull request by thibaultmeyer**
fix critical issue on JSON / XML parsing : when submitted document is empty (size: 0 bytes) or malformed, the method hasViolations() return false. This fix will correct this issue and the method hasViolations() now returning true when the document was not valid

### CODE REVIEW

**Comment by raphaelbauer** [comment]
That's pretty nice. What about using something like this:

```
        try (InputStream inputStream = context.getInputStream()) {
            t = objectMapper.readValue(inputStream, classOfT);
        } catch (JsonMappingException ex) {
            throw new BadRequestException("Error parsing incoming Json", ex);
        } catch (IOException e) {
            logger.error("Error parsing incoming Json", e);
        }
```

The BadRequestException is usually what we should use. When the request says it's a json, but can not be parsed, then it's a bad request. Let us know if that fits the bill.

Apart from that we'd need some testcases to make sure the feature is stable :)

**Comment by thibaultmeyer** [comment]
Ok, now if something goes wrong during the parsing of a JSON / XML document, the application will return a 400 error.

I have added the same behavior in the IOException catch statement to handle the case where a JSON / XML document was not "complete".

By instance, this XML document leads to an IOException during the parsing process :

```
<s>
    <first_name>John</first_name>
    <last_name>Do</last_name>
</>
```

**Comment by raphaelbauer** [comment]
That's pretty cool! It would be great if you could extend the test-cases to make sure the behaviour does not get removed by accident :)

**Comment by raphaelbauer** [comment]
Looks good :) Very nice!

**Pull request merged**
