### PR TITLE
Fix pattern for variable parts of route to handle multiple regex parts

### PR DESCRIPTION
**Pull request by bazi**
currently only one part _with regex_ can be specified in a route
making variable part regex pattern reluctant gives possibility to specify
more than one variable parts with regex

### CODE REVIEW

**Comment by gitblit** [comment]
:+1: This is a nice small change that can make a big difference in route design. It also introduces interesting overlap with `@PathParam` validation.

**Comment by bazi** [comment]
@gitblit yeah exactly! you got the reasoning behind! I needed multiple variable parts in route so that _all_ of them are _validated with regex_

**Comment by raphaelbauer** [comment]
That's pretty awesome. Actually I was thinking hard if there are potential pitfalls or problems... But this is a really great thing. Very good contribution!

Could you just add some more things.
- Add yourself to team.md
- Add one line to the changelog.md about your change
- sign the contributor's agreement https://docs.google.com/forms/d/1Yasrxa17kYfaNDgbRvn77rM3WTnU_Um0rwz3GfzPp9g/viewform

And that's it already.

I have some time the coming days and merge your contribution asap...

**Comment by bazi** [comment]
@raphaelbauer 
- added own name to team.md
- updated changelog.md
- signed contributor's agreement

**Comment by raphaelbauer** [comment]
Perfect! Thanks again for that clever piece of code!

**Comment by gitblit** [comment]
BTW, I think the docs should be updated to demonstrate the improved usefulness of regex parsing with respect to `@PathParam`.

**Comment by bazi** [comment]
@gitblit sure, I will try to propose docs update in upcoming days

**Pull request merged**
