### PR TITLE
NinjaRunner

### PR DESCRIPTION
**Pull request by smallufo**
Able to test Service Objects 
usage: 

```
@RunWith(NinjaRunner.class)
public class DataServiceTest  {

  @Inject
  private DataDao dataDao;

  @Inject
  private DataService dataService;

  @Test
  public void testDataService() {
    assert (dataDao != null);
    assert (dataService != null);
  }
}
```

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Hi smallufo,

that testrunner is really fantastic! Nice extension to the getInjector method of the NinjaTest!

There are some things we need though. 
(This might sound picky, but it is just to ensure that Ninja code stays top-quality and is maintainable in the very long run :))
- we are using 4 spaces - not 2 
- Please add some documentation to the Testrunner. A simple description on the class is enough
- Maybe a test for the testrunner? (At least one testcase in ninja-servlet-integration-test).
- We need some documentation. There is already a section about tests in the documentation - and Ninja users will really want to know about your great feature :)
- Add a single line to changelog.md.

Sounds like a lot of work? It's not :) And it really helps to promote your feature and keep Ninja stable :)

Let me know if we can help!

Cheers,

Raphael

**Comment by raphaelbauer** [comment]
That's very concise!

You are almost there!

Could you add your change to changelog.md and add the NinjaRunner documentation to testing_your_application/advanced.md. Just copy the documentation of your class to advanced.md. 

Sorry that I sound a bit picky - but I only want to make sure people know about your great feature and we can use it :) If there is no documentation on the website (via advanced.md for instance - nobody will use the great test runner :) ). Thanks!

**Comment by smallufo** [comment]
Sorry , I am not sure what should I write in changelog.md .
My version is based on 3.0.3-SNAPSHOT , but I saw 3.0.4-SNAPSHOT is out. 
I don't know what version will include this NinjaRunner . What should I do ?

(Sorry , I am not familiar with github workflow )

BTW , how do I update my local ninja to 3.0.4-SNAPSHOT ?  Modify all pom.xml beneath ninja ? (BTW , Why they are not defined in a variable ?)

**Comment by raphaelbauer** [comment]
If you want to stay in sync with the remote repo have a look at:
https://help.github.com/articles/fetching-a-remote

Then you don't have any problems with the version string :)

I'll merge your changes, add the changelog and copy your javadoc to the documentation.

Once again - nice feature :)

**Comment by raphaelbauer** [comment]
Hey smallufo,

just for the protocol. That's what I meant:
- changelog.md
- advanced.md
  and a testcase to make sure NinjaRunner works :)

https://github.com/ninjaframework/ninja/commit/583ebb4bde0070ef7621d347f15b0bed7fd613b1

Cheers,

Raphael

**Pull request merged**
