### PR TITLE
Adding Rythm template support.

### PR DESCRIPTION
**Pull request by sojin**
1) Added Rythm support in Ninja
2) Added a demo with Rythm (with Jetty 9.x)

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Pretty cool stuff! Please give me some time to review your request :)

**Comment by sojin** [comment]
Okay, I just noticed that commit df3e2ba contains the changes related to Jackson in addition to few of my changes. I believe it might be bit difficult for you to scan through them, let me know if you want me send these pull request from a new branch.

**Comment by raphaelbauer** [comment]
Hi sojin,

some remarks and ideas. The way you integrated rythm is perfect (including testcases) and also providing an integration test is awesome.

Some observations:
- When I used the ninja-core-demo-rythm (via mvn jetty:run) Rythm did not pick up my changes in the html files. How would you expect that to work?
- What is the Main class in ninja-core-demo-rythm supposed to do?
- There is I guess a tiny tutorial missing. How to set things. Where to configure rythm and so on (You already made a nice mapping from application.conf to rythm)

I have some suggestions how we can proceed from here. I'd like to move the rythm support to a separate module. That way you can take code ownership, and people that do not use rythm are not bothered. Your code is almost there. Examples are eg. https://github.com/ninjaframework/ninja-appengine.

We can put that under https://github.com/ninjaframework/ninja-rythm (with you having ownership+commit rights). I'd then organize pushing new version to maven central. Thus making it really simple for everyone to use rythm :)

Or - you maintain ninja-rythm completely outside https://github.com/ninjaframework as module. I'd then link rythm from the website so that people know your awesome work :)

Let me know what you think!
Thanks for the really good contribution!

Best,

Raphael

**Comment by sojin** [comment]
Hi Raphael,

1) As you know, jetty:run perform "redeployment" instead of "hot-deployment" upon any changes and it might take 1-4 secs until the refreshed page gets rendered. But rythm has the ability to refresh modified templates automatically in dev mode, so its better to leverage the same. I've excluded *.html in the scanTargetPattern in jetty-maven-plugin to avoid them being getting picked up by Jetty.

Can you please check again? It should work if the Ninja is in dev mode. (Rythm mode is inherited from Ninja)

2) Ah, that was just a helper class to start the app without jetty:run (similar to what you did to start the server for unit testing) and get the app debugged easily, you may remove it.

3) Yes, the documentation is missing, its on my TODO list and I've already mention about this in a mail to Ninja mailing list. https://groups.google.com/forum/#!topic/ninja-framework/pcky6kMN4Jw 

I agree with you regarding Rythm support as a module, it make sense to move it to a separate module and lets keep under Ninjaframework itself, I believe its better to have the modules together rather than scattered.

I'll wrap them and send a pull request in coming days.

Thanks
Sojin

**Comment by raphaelbauer** [comment]
Hi Sojin,

I created an empty https://github.com/ninjaframework/ninja-rythm . You are registered with full rights. Let me know if you got any problems.

Really looking forward checking out your ninja-rythm :)

Cheers,

Raphael

**Comment by raphaelbauer** [comment]
jointly declined => moved to https://github.com/ninjaframework/ninja-rythm

**Pull request closed without merging**
