### PR TITLE
UserAgent ftl switch support

### PR DESCRIPTION
**Pull request by makotan**
UserAgent ftl switch support

### CODE REVIEW

**Comment by pthum** [comment]
i suppose, that it would be nice if you would add a more detailed description to your pull requests. especially you should write what it does and why you're doing this/what you've intended to do. 
i can't imagine why it should be useful to have a structure like "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:21.0) Gecko/20100101 Firefox/21.0/views/Application/index.ftl.html" ..?

**Comment by makotan** [comment]
It is the image that sets the UserAgent in Filter.
For example, you can use it to set the Result#uaType by converting "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:21.0) Gecko/20100101 Firefox/21.0" to "firefox".
To be used on the final is "firefox/views/Application/index.ftl.html".

**Comment by raphaelbauer** [comment]
Hi Makotan,

can you describe a bit more what you are trying to achieve? What is your use case? 

A workaround for you certainly is to use Results.html().template(pathToYourUaBasedTemplate);
You can even extend Results.java to make that happen automatically for you I guess. Ninja is pretty flexible in that regard.

Best,

Raphael

**Comment by makotan** [comment]
In the beginning, I thought it was going to use a Results.html().template(...) to switch the template.
But, I noticed that you can use the same file UserAgent differ only in.
I thought there we should be able to add the UserAgent.
use case is a Web application of a special terminal for the browser installed.

**Comment by raphaelbauer** [comment]
wont-fix

**Pull request closed without merging**
