### PR TITLE
Zoza servlet integration sketch

### PR DESCRIPTION
**Pull request by raphaelbauer**
- finished the integration pls review

### CODE REVIEW

**Comment by raphaelbauer** [comment]
@zoza could you please have a look? If that's okay I'll merge it into develop...

**Comment by zoza** [comment]
1. in Module.java need to remove servlets part
2. also, next commit i want to change NinjaServletDispatcher to be a servlet and not a filter.

this is very simple:
change
filter("/_").through(NinjaServletDispatcher.class); 
to 
serve("/_").with(NinjaServletDispatcher.class);

all you need to change is <b>extends HttpServlet</b> instead of <b>extends Filter</b> in NinjaServletDispatcher.java

and replace 
<code>
public void doFilter(ServletRequest request, ServletResponse response,  FilterChain chain) throws IOException,       ServletException {
</code>

to 
<code>
 public void service(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException{
</code>

**Comment by raphaelbauer** [comment]
Hi zoza... thanks regarding the module.java. I overlooked that one.

Regarding filter - to -servlet switch. Please feel free to change and push. I think that's a really good thing to do. There were some people that had problems running ninja as filter... 

Cheers,
Raphael

**Comment by zoza** [comment]
Hi.
Because im still not guru with git and github, i will wait, till you done
merge and then do this change

**Pull request merged**
