### PR TITLE
Ticket #595

### PR DESCRIPTION
**Pull request by christiangroth**
https://github.com/ninjaframework/ninja/issues/595

removed call to close as this also calls stop internally and leads to duplicate metric updates

### CODE REVIEW

**Comment by raphaelbauer** [comment]
The tiny problem is that we might run into regressions later on. Imagine someone just adding that line accidentally again.
Therefore it would be great having a mocked test that tests that close is called only once (and stop never maybe).

Afaics there is no test yet for this class (which is ugly anyway). So you'd be the first and could greatly increase the stability :)

What I imagine is really just a test that uses mocks and makes sure close is called once (and stop never)...

Would you mind adding that? Let me know if you need any hints.. Thanks!

**Comment by christiangroth** [comment]
Done! :)

**Comment by christiangroth** [comment]
@raphaelbauer Any feedback on this one?

**Comment by christiangroth** [comment]
Also updated changelog here

**Comment by christiangroth** [comment]
@raphaelbauer: Any comments on this one? Would be great to have this also merged!

**Comment by raphaelbauer** [comment]
Thanks for pinging! 👍

**Pull request merged**
