### PR TITLE
Flyway upgrade from 2.3.1 to 3.2.1 (fix many problems)

### PR DESCRIPTION
**Pull request by danielsawan**
Hi there. This is my very first pull request ever so i am still discovering how all this work.
I had many problem using Flyway with ninja but not any problem using flyway standalone client. 

After some research I saw that the Flyway version used in Ninja was very old 2012/2013 so I decided to update it to the last version (2015).

After this update I had no more problem using flyway in Ninja !

PS : in only tested the basic usage (mine). This pull request don’t cover all the required tests. (at least I guess).

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Nice! Could you update changelog.md to reflect the change? Thanks!

**Comment by liudianpeng** [comment]
Java linkage how to write

**Comment by liudianpeng** [comment]
@raphaelbauer

**Comment by raphaelbauer** [comment]
Nice work!

**Pull request merged**
