### PR TITLE
Added error message when no bodyparser for the content type was availabl...

### PR DESCRIPTION
**Pull request by eicnix**
When no Content-Type is sent the Content-Type "_/_" is used and because there is no default BodyParserEngine for this Content-Type a body request parse will always fail. 

The added error message should show the user that he needs to declare a proper Content-Type to automatically parse request bodies.

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Very helpful!
Two things:
1) Would you mind signing the contributor's agreement? 
2) Could you add one line to changelog.md. I know - the change looks small, but it's nevertheless cool to know who has contributed what to each release :) Small-looking usability enhancements like yours are sometimes more important than huge badass features :)

**Comment by gitblit** [comment]
It's great to log this... But perhaps the error should also be returned to the request origin as 'text/plain' ?

**Comment by eicnix** [comment]
@raphaelbauer The agreement is signed and the changelog.md updated
@gitblit This there already an mechanism to abort the request processing and response and error?

**Comment by raphaelbauer** [comment]
Merged the PR separately ({} is more perfomant than + in Strings).

Check out:
https://github.com/ninjaframework/ninja/blob/develop/ninja-servlet/src/main/java/ninja/servlet/ContextImpl.java

Thanks for your contribution! :)

**Pull request merged**
