### PR TITLE
Log the resolved routes on Ninja startup

### PR DESCRIPTION
**Pull request by gitblit**

### CODE REVIEW

**Comment by gitblit** [comment]
Grrrr.  Eclipse doesn't like the redefine-the-package capability used in ninja-servlet.  _sigh_.  Will fix PR shortly.

**Comment by gitblit** [comment]
This _seems_ like a bug to me in the unit test structure of ninja-servlet.  I actually don't understand how they pass at all on CloudBees.  There is an import/package name problem which I have assumed is related to the package redefinition feature.  If I fix it locally, I can run all Maven tests nicely.  If I leave it stock, it fails.  It is confusing me how CloudBees can turn up successful builds of the same code.

Specifically, **controller**.DummyControllerForTesting needs to be **controllers**.DummyControllerForTesting

**Comment by gitblit** [comment]
I haven't forgotten about this.  Will get back to it next week.  Right now routes without controllers and methods are ignored - so that is actually undesirable.  Will fix.

**Comment by gitblit** [comment]
@raphaelbauer Maybe you can review this weekend.

**Comment by raphaelbauer** [comment]
sorry... thanks for reminding me! :)

**Pull request merged**
