### PR TITLE
Added  ninja.idle.timeout command line parameter for stand alone mode

### PR DESCRIPTION
**Pull request by raptaml**

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Very nice! Also very cool that you extended the testcase.
Could you add your change to changelog.md?

Then we'll merge asap!

**Comment by raptaml** [comment]
Thanks!
Edited the changelog file just now.

**Comment by raptaml** [comment]
So now it is in one PR.

**Comment by raphaelbauer** [comment]
very nice!

**Pull request merged**
