### PR TITLE
Dev mode only ftl auto reload

### PR DESCRIPTION
**Pull request by makotan**

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Hey thanks :)

what does this actually fix? Or what is the problem you are encountering?

Raphael

**Comment by makotan** [comment]
only when the dev mode, reflected in the modification of reload ftl.html

**Comment by raphaelbauer** [comment]
okay I see...
The thing is => I usually use Ninja together with jetty that reloads when something new is in the target directory. Eclipse on the other hand copies new stuff from src over to target when I change something. That means I modify a ftl.html file, eclipse copies it over to target, jetty restarts and I get my new ft.html.

Doesn't that work for you? 

Thanks :)

**Comment by makotan** [comment]
restart of the jetty will be unnecessary.Is it still required?

**Comment by raphaelbauer** [comment]
Hmm.
I agree that a restart of jetty is totally unnecessary.
On the other hand.
I start jetty usually on the command line mvn jetty:run
=> it then picks up changes in its classes directory.

Eclipse by default copies the classes anyhow into the classes directory and triggers a Jetty reload.

So in my case - even if we point the ftl.html to the sources directory => it will trigger a reload in my case anyways...

My question:
How do you start Ninja? Via maven?

**Comment by makotan** [comment]
is via maven
I makes frequent modification of ftl. And I would like to see the results quickly.

**Comment by raphaelbauer** [comment]
How did you configure jetty not to restart when a ftl.html changes (I assume your IDE copies over the file to the target dir when changed)..?

**Comment by makotan** [comment]
Only when dev mode,I was changed from setClassForTemplateLoading to setDirectoryForTemplateLoading.
To get the path from System.getProperty("user.dir"), and added "/src/main/java"

**Comment by raphaelbauer** [comment]
thanks! very good feature :)

**Pull request merged**
