### PR TITLE
add new jvmArgs property, allows to add arguments to the embedded jetty

### PR DESCRIPTION
**Pull request by momiji**
this may replace my other PR as I now understand that I should not use "develop" branch...

### CODE REVIEW

**Comment by momiji** [comment]
OK this PR is finished, can be reviewed and merged ;)

**Comment by raphaelbauer** [comment]
Very well done! Good documentation.

Can you think of a test that makes sure we don't break the feature unintentionally? 
- Somehow it would be cool to make sure the array is populated properly on init
- And that splitUnescapedSpaces works properly (make it protected and write a simple test would be pragmatic eg).

**Comment by momiji** [comment]
I'll have a look, but don't how to do the first one. I'll add some tests for the second one.

**Comment by noguespi** [comment]
great PR, that's what I need

**Comment by noguespi** [comment]
Can it be merged for next release or do we have to wait for #409 ?

**Comment by raphaelbauer** [comment]
I'll merge this as part of #409 . You are mentioned as contributor... Great stuff :) (Declining the PR therefore)

**Pull request closed without merging**
