### PR TITLE
Fixes issue #354

### PR DESCRIPTION
**Pull request by ghost**
Reverse routing with multiple regex parameters produced broken URLs.

### CODE REVIEW

**Comment by raphaelbauer** [comment]
that's pretty cool! Catching a bug and fixing it immediately is great!
We'd need a testcase that makes sure the issue you mentioned does not surface again. Then add yourself to team.md and add one line to the changelog.md. Please also make sure you signed the contributor's agreement (More here: http://www.ninjaframework.org/developer/getting_started.html).

**Comment by ghost** [comment]
Added a test case, updated changelog.md and added myself to team.md.

**Comment by raphaelbauer** [comment]
Welcome to the team! And thanks for your contribution!

**Comment by ghost** [comment]
Thanks for Ninja Framework!

**Comment by raphaelbauer** [comment]
It's all about contributors like you :) It's the community that makes it great!

**Pull request merged**
