### PR TITLE
Adding JsonP support

### PR DESCRIPTION
**Pull request by nobullet**

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Really nice. Even with documentation! I'll check it out in detail asap :)

**Comment by raphaelbauer** [comment]
Hi @nobullet,

your code looks fantastic, changelog and documentation - all there :+1: 
I'd like to see three more things:
1) A mocked unit test for TemplateEngineJsonP in project ninja-core.
2) A simple integration test in project https://github.com/ninjaframework/ninja/tree/develop/ninja-servlet-integration-test. A simple endopont that returns the jsonp snipplet and a testcase that checks if the result of the html page is correct.
3) Please add yourself to https://github.com/ninjaframework/ninja/blob/develop/ninja-core/src/site/markdown/team.md

Please let me know if you got any questions - we are here to help. And sorry for the need for additional testcases - but if we want Ninja to be stable we simply need them :)

Thanks!

Raphael

**Comment by nobullet** [comment]
Hi @raphaelbauer.
1. Done.
2. Done.
3. Already in team.md

Please review the CL again.

**Comment by raphaelbauer** [comment]
Very good feature and code!

**Pull request merged**
