### PR TITLE
Context attributes and multivalued headers

### PR DESCRIPTION
**Pull request by tbroyer**
- make headers multivalued
- add `getParameterValues`; I find a never-null `List` saner than a never-empty nullable array.
- add `Context` attributes, with `@Attribute` argument extractor.

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Awesome stuff Thomas!

Three quick and minor things:
1. Do you think it makes sense to add testcases at least in ContextImplTest of ninja-servlet against the new attributes stuff? Just to make sure stuff does not break.
2. changelog.md in ninja-core/src/site/markdown/developer should be updated reflecting the new features
3. And then there was a tweet recently saying "Looks like Ninja framework lacks documentation more than features (like so many OSS projects, starting with my owns)" (just kidding) - but docs are missing... they also live in ninja-core/src/site/markdown/ .

Just tell me if you got time to do that. I can handle that as well :) Apart from that really nice work.

**Comment by tbroyer** [comment]
On Tue, Apr 9, 2013 at 2:15 PM, Raphael A. Bauer
notifications@github.com wrote:

> Awesome stuff Thomas!
> 
> Three quick and minor things:
> 1. Do you think it makes sense to add testcases at least in ContextImplTest of ninja-servlet against the new attributes stuff? Just to make sure stuff does not break.

Attributes are so simple I don't think adding tests makes sense.
I'm ambivalent about adding tests for getParameterValues or getHeaders(String).

> 1. changelog.md in ninja-core/src/site/markdown/developer should be updated reflecting the new features

Will do.

> 1. And then there was a tweet recently saying "Looks like Ninja framework lacks documentation more than features (like so many OSS projects, starting with my owns)" (just kidding) - but docs are missing... they also live in ninja-core/src/site/markdown/ .
> 
> Just tell me if you got time to do that. I can handle that as well :) Apart from that really nice work.

TBH, I'd prefer you update the documentation (that new "Request
Scopes" page you added yesterday). I'd be tempted to replace the
"WrappedContext in Filters" section altogether.
If it's OK for you, tell me and i'll do it; otherwise I'll let you
enhance the doc.

**Comment by raphaelbauer** [comment]
On Tue, Apr 9, 2013 at 4:04 PM, Thomas Broyer notifications@github.comwrote:

> On Tue, Apr 9, 2013 at 2:15 PM, Raphael A. Bauer
> notifications@github.com wrote:
> 
> > Awesome stuff Thomas!
> > 
> > Three quick and minor things:
> > 1. Do you think it makes sense to add testcases at least in
> > ContextImplTest of ninja-servlet against the new attributes stuff? Just to
> > make sure stuff does not break.
> 
> Attributes are so simple I don't think adding tests makes sense.
> I'm ambivalent about adding tests for getParameterValues or
> getHeaders(String).

If you don't think it makes sense - don't do it.

> > 1. changelog.md in ninja-core/src/site/markdown/developer should be
> >    updated reflecting the new features
> 
> Will do.
> 
> Cool...
> 
> > 1. And then there was a tweet recently saying "Looks like Ninja
> >    framework lacks documentation more than features (like so many OSS
> >    projects, starting with my owns)" (just kidding) - but docs are missing...
> >    they also live in ninja-core/src/site/markdown/ .
> > 
> > Just tell me if you got time to do that. I can handle that as well :)
> > Apart from that really nice work.
> 
> TBH, I'd prefer you update the documentation (that new "Request
> Scopes" page you added yesterday). I'd be tempted to replace the
> "WrappedContext in Filters" section altogether.
> If it's OK for you, tell me and i'll do it; otherwise I'll let you
> enhance the doc.

Just replace and enhance my part. If I can contribute let me know :)

ra

**Comment by tbroyer** [comment]
Finally added a section to "Request Scopes" and kept the one about `WrappedContext` (slightly reformulated).

Also, added `@Attribute` argument extractor.

**Comment by raphaelbauer** [comment]
This is truly awesome!

**Pull request merged**
