### PR TITLE
Grizzly support, incomplete Netty support

### PR DESCRIPTION
**Pull request by tbroyer**
I can't get Netty to work, but I included the commit anyway.

I tested Grizzly by slightly modifying the `ninja-core-demo` (changed to `jar` packaging, added `src/main/webapp` as a `<resource>` mapped to `META-INF/resources`; I also used the `maven-shade-plugin` to build an executable uber-jar, but I think I only ever launched the server from within my IDE).
Note that one file is licensed under CDDL+GPL.

Feel free to do whatever you want with this code.

### CODE REVIEW

**Comment by tbroyer** [comment]
Ah, coded against Java 7… (BTW, I can't remember what that _FIXM_E is for)

**Comment by raphaelbauer** [comment]
Hi Thomas,

this is really awesome! Unfortunately I am really busy right now. Do you need this merge request immediately? Because I'd like to have a deep look first before I merge things. There should be at least a range of testcases / integration tests that make sure grizzly (and potentially netty) support is working properly (well - that is obvious) :)

Actually I wanted to make a hackathlon in Berlin soon, and this is a really cool basis for a hackathlon project :)

I'd also love to see performance figures for that... (Techempower benchmark ;) )...

Great stuff...

Cheers,

Raphael

**Comment by tbroyer** [comment]
Hi Raphael,

As I said on my [blog post](http://blog.ltgt.net/ninja-jaxrs-and-servlets) and on [Google+](https://plus.google.com/113945685385052458154/posts/UneFVuF3myS#z12owjv4lyn3ed45a04chvtwjuz3xj4igg4%231366295510179493), I don't think I'll use Ninja; so I'm only releasing the code I've been working on, for others to use. So feel free to do whatever you want with this code (including simply ignoring it and closing this pull-request, I don't mind), I don't _need_ it. As a corollary, don't expect me to do any more work on it, including benchmarks. This is only about liberating code that I've spent a few hours working on and others might need or want to play with.

**Comment by raphaelbauer** [comment]
That's perfect :) Thanks for your efforts!

**Comment by raphaelbauer** [comment]
I'll close the PR for now. Thanks for your contribution :)

**Pull request closed without merging**
