### PR TITLE
flyway version bump to 4.0

### PR DESCRIPTION
**Pull request by nate-kingsley**

### CODE REVIEW

**Comment by nate-kingsley** [comment]
looked at the travis logs; looks like the 1.7 stalled out (no Failures, but the following message is at the end of the raw log: "No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself."). Want me to close/reopen PR or would you rather just rerun via travis? @jjlauer @raphaelbauer

**Comment by raphaelbauer** [comment]
Pretty cool! CI passed. Thanks for your contribution!

Did you already sign the contributor's agreement and did you add yourself to team.md already?

**Comment by nate-kingsley** [comment]
@raphaelbauer Thanks for the reply! Yeah, i've already signed the agreement and the PR contains the addition to the team.md (along with the note in the changelog for the version bump). Hopefully this helps. Keep up the great work on this!

**Comment by raphaelbauer** [comment]
Perfect. You are part of the "great work" :) Thanks!

**Pull request merged**
