### PR TITLE
 #561 Make scheduling support a feature of NinjaClassicModule

### PR DESCRIPTION
**Pull request by patrickabner**

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Thanks for the PR. Makes total sense to me.

@jjlauer ack?

**Comment by jjlauer** [comment]
Yeah, makes sense to me too.  I'd recommend we make notes in the CHANGELOG though since this may potentially break some apps.

**Comment by raphaelbauer** [comment]
Cool. So let's go for it...

Please add your change to changelog.md and upgrade_guide.md. If you are not yet a contributor make sure to also agree here: https://docs.google.com/forms/d/1Yasrxa17kYfaNDgbRvn77rM3WTnU_Um0rwz3GfzPp9g/viewform

Then we can merge it.
Thanks!

**Comment by raphaelbauer** [comment]
Thanks for your contribution!

**Pull request merged**
