### PR TITLE
Ninja DAO abstract class helper

### PR DESCRIPTION
**Pull request by emiguelt**
Dao Test Base class to help testing real DAOs using JPA

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Pretty cool @emiguelt!

Some minor things:
- I guess it would make sense to add a@After method that calls  persistService.stop(); or did I miss something?
- It would be great if you could add some documentation to ninja-core/src/site/markdown/testing.html. Your commit is pretty cool and the others should know about it :)

And last but not least please add a tiny snippet to changelog.md and also team.md (as described here: http://www.ninjaframework.org/developer/getting_started.html)

I'll merge and release that asap...

Cheers,

Raphael

**Comment by emiguelt** [comment]
Hi @raphaelbauer!
Thanks a lot for checking my PR.

About the _persistenceService.stop()_, before I had a _jpaInitializer.stop()_ in a @after method, but it generates a _java.lang.Exception: DEBUG -- CLOSE BY CLIENT STACK TRACE_. I read about this error and it is not a real exception (http://stackoverflow.com/questions/8403227/weird-error-close-by-client-stack-trace) . In anyway I decided to remove the _stop()_ call and avoid this error message. I checked it and all is working ok.

About other suggestions, I added some documentations about the NinjaDaoTestBase class.

Best,

Miguel

**Comment by raphaelbauer** [comment]
Hi @emiguelt,

I think shutting down the JPA connection is important. If we don't do this this might result in blocked connections - especially when connecting to real db systems. But the solution to the stupid error message is simple. And actually this is something we should have done way before. All logback.xml files of Ninja are currently set to <root level="debug">. We should change that to <root level="info"> in all logback files...

This helps a lot to separate noise from real error messages...

What do you think?

Raphael

**Comment by raphaelbauer** [comment]
I just changed the loglevel of the archetypes and the integration tests to "info". Please let me know if that works for you...

**Comment by emiguelt** [comment]
Hi Raphael,
Done, I annotated two methods to initialize and stop the persistence service with the JUnit lifecycle.
Best,
Miguel :)

**Comment by raphaelbauer** [comment]
nice!

**Pull request merged**
