### PR TITLE
Added dependency for ibm icu4j.

### PR DESCRIPTION
**Pull request by JuanCaicedo**
Added icu4j dependency to pom.xml.
Switched MessageFormat import statement in MessagesImpl and Messages.
Deleted MessageFormat import statement in FlashScope.

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Hey Juan,

did you replace it because of the ticket or do you have something else in mind?

Currently to get "that's me" we have to write in that''s me" in messages.properties. icu4j has a special mode ApostropheMode where you can configure that. I did not have a look into that - do you think it's possible to configure that globally so that we can use a better apostrophe formatting in messages.properties?

Thanks for your work!

Best,

Raphael

**Comment by JuanCaicedo** [comment]
Hi Raphae, 
I just followed the ticket thinking I'd start contributing with small steps. Let me look into ApostropheMode!
Cheers,
Juan

**Comment by raphaelbauer** [comment]
If you need more information let me know :) I'd be pleased to assist! Cheers,

Raphael

**Comment by JuanCaicedo** [comment]
Actually, I had some trouble figuring out how to integrate changes in the source with the application I created using the archetype generation. Do you have any resources from building from source?
Thanks!
Juan

**Comment by raphaelbauer** [comment]
Where is the problem exactly? You can clone the Ninja repository and then call mvn install in its root. 
Make sure you are referencing the -SNAPSHOT version you've just built and you are ready to go... Let me know if that makes sense... 
You can also ask on our mailing list - lots of friendly and helpful folks :)

**Pull request closed without merging**
