### PR TITLE
Handle empty string param parsing

### PR DESCRIPTION
**Pull request by jlannoy**
For each parameter that is not a string, the parameter is checked against null and then against an empty string. In both case, the returned value for that parameter is null.

There is one exception, it's for the String parameters... An empty string (input) results in a empty string (parameter value). It could seems legit but I don't think it is. When an HTML request POST form fields that have not been filled, they appear in the request with... an empty value. Meaning that with the current version of Ninja, you have to check if your string is empty to know if user has entered a value in it. All my projects and my colleagues projects, are overriding the StringParamParser to avoid that.

There could be an side effect. Let's say we have... ?var=&var2=b 
With what I said just before, it means that the var param would be null. So you would not be able to make a difference between ?var=&var2=b and ?var2=b. But is it an issue? Does it make sense to explicitly want to pass an empty string to a parameter? I don't see any case where it could be a good use case.

I think it makes even more sense since with have Optional parameters for cleaner solutions. What do you think?

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Thanks for the PR :)

I'll cross post it on the mailing list - to make sure that people can comment. I don't yet have an opinion (and did not run into that issue). Give me some time to check some things out...

@jjlauer do your apps run into that problem?

**Comment by raphaelbauer** [comment]
I am undecided. I've seen that other frameworks do it differently (and accept "empty" parameters as empty strings).

But I also don't care and my apps are not affected by that change. @jjlauer also got a valid point. So we can do it.

Before we can merge the change please do the following:
- Add your change to changelog.md and upgrade_guide.md.
- Update the documentation to highlight the parameter handling (Maybe a box with some notes).

Thanks for the nice contribution!

**Comment by raphaelbauer** [comment]
For the record. That's @jjlauer 's comment from the mailing list:

> I agree that empty strings are as good as null strings from a
> parameter perspective.  I'm an advocate for making parameter parsing
> pretty strict.  It makes the new Optional concept better too since you
> can supply a default if the user didn't really provide one.

**Comment by jlannoy** [comment]
@raphaelbauer And what about a configuration property to let users choose the way it work?

**Comment by raphaelbauer** [comment]
Theoretically yes - but that always takes maintenance effort in the long run. So I don't like it too much. And nobody objected, so I guess it's safe to change the behaviour...

**Comment by raphaelbauer** [comment]
Thanks @jlannoy for your contribution! Will be released asap :)

**Pull request merged**
