### PR TITLE
Added convert string parameter to other class type

### PR DESCRIPTION
**Pull request by amsz**

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Hi amsz,

I added some tiny tings. Eg the converter method now returns null when something goes wrong and no longer throws a Runtime exception (this will stop the server)...

Very good job!

Cheers,

ra

**Comment by amsz** [comment]
It is a beautiful change, but it may be introduce a bug in BodyParserEnginePost.invoke(), I just catch a UnsupportedOperationException if convert fail, now should judge if it is null.

**Comment by raphaelbauer** [comment]
Hey amsz,

very good catch! you are absolutely right. On the other hand the code was a bit buggy anyway - because setting a not supported Field type (like let's say StringBuffer) to the incoming String does not make sense either.

I added a testcase and rewrote the stuff. If something is not supported and cannot be converted it will become null.

Let me know what you think (it's already in develop) :)

Cheers,

Raphael

**Comment by amsz** [comment]
I have no good idea, may be expose a method that user can register a custom type convertor, like BodyParserEngine::register(String contextType, Class<T> classOfT, BodyConvert convert)

**Pull request merged**
