### PR TITLE
handle of uploaded files the same way as normal query and form fields

### PR DESCRIPTION
**Pull request by momiji**
I hope everything is inside, includin documentation, integration tests, unit tests, ...

### CODE REVIEW

**Comment by momiji** [comment]
OK this PR is finished, can be reviewed and merged ;)

**Comment by bazi** [comment]
why is this PR closed @momiji ?

**Comment by momiji** [comment]
Because it is finished, no more work is needed. Is it wrong?

**Comment by momiji** [comment]
but it can be reopened if preferable...

**Comment by bazi** [comment]
PR is opened to be merged, if not merged for some reasons then it is closed. Closed ones can not be merged.
In our case, PR #368 is closed in preference to this PR. So this one should be open.

**Comment by raphaelbauer** [comment]
Hey @momiji and @bazi - what is the state of affairs? Do you have a consensus about the next generation uploading Api? Which PR is relevant? Thanks!

**Comment by bazi** [comment]
PR ~~#368~~ proposed by me was closed in preference to this one. So this PR shall be considered for file uploading.

**Comment by raphaelbauer** [comment]
Excellent work! This PR looks truly awesome :) It is actually too good to be true because it contains everything we need in very high quality: Very nice implementation, good tests and simple documentation! Congrats to the contributors!

I'll ask on the mailinglist for comments - just to make sure we don't leave anyone behind. Will be merged soon.

**Comment by jjlauer** [comment]
I know its late, but I was thinking that List<> types rather than an array would be more useful w/ Java 8.  The Context object sort of uses both right now and it'd be good to eventually deprecate arrays in favor of collections.

**Comment by raphaelbauer** [comment]
True... I did not yet write the offical release note... So if you want we can still change that and announce 5.2.1 before it is adopted... :)

**Comment by jjlauer** [comment]
Yes, if there was any time to adjust it, it would be now.  Will submit a PR
today.

**Pull request merged**
