### PR TITLE
added the possibility to move a ninja application to any package

### PR DESCRIPTION
**Pull request by jbarop**
Adresses issue #61

Needs some properly testing because I'm totaly uncertain if I found all occurrences. I'm also uncertain if it's a good idea to make NinjaPath.getXXX static. But this makes it a lot easier to use as utility class.

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Unfortunately I do not have time to test it extensively right now. And I
would not merge it into develop without rigid testing.

Is this merge really urgent - or would it be okay if I check it out in Jan
2013?

Thanks!

Raphael

On Thu, Nov 29, 2012 at 9:00 PM, BuildHive notifications@github.com wrote:

> reyez » ninja #193https://buildhive.cloudbees.com/job/reyez/job/ninja/193/SUCCESS
> This pull request looks good
> (what's this?) https://www.cloudbees.com/what-is-buildhive
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/reyez/ninja/pull/63#issuecomment-10863742.

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by jbarop** [comment]
I agree that this needs some solid testing. I just tested it with the ninja-core-demo

It's not urgent for me. I'll use it in my new project (wohoo, testing) and can rely on my SNAPSHOT build for now

**Comment by raphaelbauer** [comment]
One quick remark (to myself?): We have to make sure that the integration of third party plugins does not get broken. Especially regarding mapping of views and the views directory of external plugins...

**Comment by jbarop** [comment]
any progress on this one?

if you can give a hint with this plugin stuff i can check it out

**Comment by avarabyeu** [comment]
Guys, any progress on this issue? Looks like this thread is died

**Comment by raphaelbauer** [comment]
Hi everyone,

the feature was contributed by the community and is already part of Ninja :)

Thanks for the discussion and the ideas!

Closing this...

Raphael

**Pull request closed without merging**
