### PR TITLE
Upgrade archetypes / replace assembly with shade

### PR DESCRIPTION
**Pull request by thibaultmeyer**
Hi,

Here the pull request for the issue #291 .
- Replace maven plugin "assembly" with "shade"
- Upgrade Bootstrap from 3.3.2 to 3.3.4
- Upgrade H2 driver from 1.4.182 to 1.4.186
- Fix 404 error with TinyMCE jquery plugin in "defaultLayout.ftl.html"
- Remove the unneeded TinyMCE dependency in "ninja-servlet-archetype-simple" archetype

### CODE REVIEW

**Comment by raphaelbauer** [comment]
Hey @0xbaadf00d, 

very nice and valuable contribution! Some things I'd like to add:
1) Please also remove the assembly plugin from the other pom.xml files (and also update the versions of bootstrap / tinymce there, too).
2) Very important - the documentation has to be updated as well. The relevant file is called "ninja_standalone.md" (in ninja-core/src/main/site/...).

By the way - It's nice that you also updated the versions of bootstrap / tinymce - if you want to speed up the merge it would be cool if you could create separate PRs next time :) It's actually quite hard to merge PRs that contain more than one feature. Thanks!

Raphael

**Comment by thibaultmeyer** [comment]
Hi,

I'm sorry about this, I will take care next time. Ok for  (1) and (2); I'll let you know when I finish.

**Comment by raphaelbauer** [comment]
no need to be sorry!  It's just a remark - it happened in the past that several PRs contained simply too many changes and it was impossible to review them... Your stuff is great :)

**Comment by thibaultmeyer** [comment]
Hi Raphael,

after a little grep, they are a Bootstrap webjar without version specified in a lot of "pom.xml"; and I found directly the file "bootstrap.min.js" in some directories (in version 3.0.0).

All this files need to be upgraded to 3.3.4 ?

**Comment by raphaelbauer** [comment]
afaics bootstrap webjar is used in nninja-servlet-archetype-simple, ninja-servlet-integration-test, ninja-servlet-jpa-blog-archetype and ninja-servlet-jpa-blog-integration-test. If we bump the version (and update tinymce) it should be updated in all those projects :) We should keep the versions uniform across the project.

**Comment by thibaultmeyer** [comment]
ok, thanks for your help.

Now, all sub-project are up to date and use Bootstrap 3.3.4.  The documentation is upgraded too.

**Comment by raphaelbauer** [comment]
Merged locally. Very nice contribution! Thanks!

**Comment by thibaultmeyer** [comment]
you're welcome

**Pull request merged**
